/* eslint-disable */
/* tslint:disable */
/**
 * This is an autogenerated file created by the Stencil compiler.
 * It contains typing information for all components that exist in this project.
 */
import { HTMLStencilElement, JSXBase } from "@stencil/core/internal";
export namespace Components {
    interface YourComponent {
        /**
          * The first name
         */
        "first": string;
        /**
          * The last name
         */
        "last": string;
        /**
          * The middle name
         */
        "middle": string;
    }
}
declare global {
    interface HTMLYourComponentElement extends Components.YourComponent, HTMLStencilElement {
    }
    var HTMLYourComponentElement: {
        prototype: HTMLYourComponentElement;
        new (): HTMLYourComponentElement;
    };
    interface HTMLElementTagNameMap {
        "your-component": HTMLYourComponentElement;
    }
}
declare namespace LocalJSX {
    interface YourComponent {
        /**
          * The first name
         */
        "first"?: string;
        /**
          * The last name
         */
        "last"?: string;
        /**
          * The middle name
         */
        "middle"?: string;
    }
    interface IntrinsicElements {
        "your-component": YourComponent;
    }
}
export { LocalJSX as JSX };
declare module "@stencil/core" {
    export namespace JSX {
        interface IntrinsicElements {
            "your-component": LocalJSX.YourComponent & JSXBase.HTMLAttributes<HTMLYourComponentElement>;
        }
    }
}
